# Generated by Django 6.0.1 on 2026-01-31 22:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ensayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('unit', models.CharField(default='KG', max_length=10)),
                ('is_base_flour', models.BooleanField(default=False, help_text='Flag for PPM calculation base')),
                ('is_active', models.BooleanField(default=True)),
                ('default_price', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.CreateModel(
            name='EnsayoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity in KG', max_digits=10)),
                ('dosage_ppm', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='lab.ensayo')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='lab.client')),
            ],
        ),
        migrations.AddField(
            model_name='ensayo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensayos', to='lab.project'),
        ),
        migrations.CreateModel(
            name='ProjectIngredientPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.ingredient')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.project')),
            ],
            options={
                'unique_together': {('project', 'ingredient')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='custom_prices',
            field=models.ManyToManyField(through='lab.ProjectIngredientPrice', to='lab.ingredient'),
        ),
    ]
