# Generated by Django 6.0.1 on 2026-02-01 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_client_options_alter_ensayo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('Molino', 'Molino'), ('Panificadora', 'Panificadora'), ('Panadería Artesanal', 'Panadería Artesanal'), ('Otro', 'Otro')], default='Otro', max_length=50, verbose_name='Tipo de Cliente'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contacto 1 (Nombre/Tel)'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contacto 2 (Nombre/Tel)'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contacto 3 (Nombre/Tel)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email General'),
        ),
        migrations.AlterField(
            model_name='client',
            name='maps_url',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace Google Maps'),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='code',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='Código de Ensayo'),
        ),
        migrations.CreateModel(
            name='EnsayoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ensayo_photos/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nota (ej: Miga, Alveolado)')),
                ('ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lab.ensayo')),
            ],
            options={
                'verbose_name': 'Imagen de Ensayo',
                'verbose_name_plural': 'Galería de Imágenes',
            },
        ),
    ]
