# Generated by Django 6.0.1 on 2026-02-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_remove_ensayodetail_dosage_ppm'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensayo',
            name='gluten',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Gluten Húmedo %'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humedad %'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='pl_relacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='P/L'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='w_fuerza',
            field=models.IntegerField(blank=True, null=True, verbose_name='W (Fuerza)'),
        ),
    ]
