# Generated by Django 6.0.1 on 2026-02-02 00:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0007_alter_ensayoimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensayodetail',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=15, verbose_name='Precio por KG ($)'),
        ),
    ]
