# Generated by Django 6.0.1 on 2026-02-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0008_ensayodetail_price_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de Contacto'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono / WhatsApp'),
        ),
        migrations.AddField(
            model_name='client',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cargo / Puesto'),
        ),
    ]
