# Generated by Django 6.0.1 on 2026-02-02 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0010_client_contacts_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='lab.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='visit',
            name='objective',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Objetivo / Temática'),
        ),
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Realizada', 'Realizada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=50, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('Técnica', 'Técnica'), ('Comercial', 'Comercial'), ('Seguimiento', 'Seguimiento'), ('Otro', 'Otro')], default='Técnica', max_length=50, verbose_name='Tipo de Visita'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Bitácora / Reporte de Visita'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='lab.project', verbose_name='Proyecto'),
        ),
    ]
