# Generated by Django 6.0.1 on 2026-02-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0012_project_fixed_fee_visit_expenses_visit_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='kilometers',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Kilómetros Recorridos'),
        ),
    ]
