# Generated by Django 5.1.6 on 2026-02-09 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0014_project_technical_observations'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL("CREATE TABLE IF NOT EXISTS lab_technicalreport (id bigserial PRIMARY KEY);"),
                migrations.RunSQL("ALTER TABLE lab_technicalreport ADD COLUMN IF NOT EXISTS report_date date;"),
                migrations.RunSQL("ALTER TABLE lab_technicalreport ADD COLUMN IF NOT EXISTS start_date date;"),
                migrations.RunSQL("ALTER TABLE lab_technicalreport ADD COLUMN IF NOT EXISTS end_date date;"),
                migrations.RunSQL("ALTER TABLE lab_technicalreport ADD COLUMN IF NOT EXISTS technical_observations text;"),
                migrations.RunSQL("ALTER TABLE lab_technicalreport ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();"),
                migrations.RunSQL("ALTER TABLE lab_technicalreport ADD COLUMN IF NOT EXISTS project_id bigint;"),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='TechnicalReport',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('report_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Informe')),
                        ('start_date', models.DateField(verbose_name='Fecha Inicio Rango')),
                        ('end_date', models.DateField(verbose_name='Fecha Fin Rango')),
                        ('technical_observations', models.TextField(verbose_name='Observaciones Técnicas / Conclusiones')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='lab.project', verbose_name='Proyecto')),
                    ],
                    options={
                        'verbose_name': 'Informe Técnico',
                        'verbose_name_plural': 'Historial de Informes Técnicos',
                        'ordering': ['-report_date', '-created_at'],
                    },
                ),
            ]
        ),
    ]
