# Generated by Django 5.1.6 on 2026-05-25 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0022_alter_complaintimage_image_alter_ensayoimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_quote', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cotización al Cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='lab.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Presupuesto de Proyecto',
                'verbose_name_plural': 'Presupuestos de Proyectos',
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Visitas', 'Visitas'), ('Ensayos', 'Ensayos'), ('Insumos', 'Insumos'), ('Horas Asesor', 'Horas Asesor'), ('Otros', 'Otros')], default='Otros', max_length=50, verbose_name='Tipo de Ítem')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio Unitario')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lab.projectbudget', verbose_name='Presupuesto')),
            ],
            options={
                'verbose_name': 'Ítem de Presupuesto',
                'verbose_name_plural': 'Ítems de Presupuesto',
            },
        ),
    ]
