# Generated by Django 6.0.1 on 2026-02-01 03:05

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='ensayo',
            options={'verbose_name': 'Ensayo', 'verbose_name_plural': 'Ensayos de Laboratorio'},
        ),
        migrations.AlterModelOptions(
            name='ensayodetail',
            options={'verbose_name': 'Línea de Receta', 'verbose_name_plural': 'Formulación de la Receta'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Ingredientes'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='projectingredientprice',
            options={'verbose_name': 'Precio por Proyecto', 'verbose_name_plural': 'Precios por Proyecto'},
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Contacto'),
        ),
        migrations.AddField(
            model_name='client',
            name='cuit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CUIT'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contacto'),
        ),
        migrations.AddField(
            model_name='client',
            name='maps_url',
            field=models.URLField(blank=True, help_text='Enlace directo a la ubicación en Google Maps', null=True, verbose_name='Enlace Google Maps'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='ash_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='Cenizas (%)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='baked_volume_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Altura Horneado (cm)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='baked_weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Horneado (g)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='baking_type',
            field=models.CharField(blank=True, choices=[('Fermentado', 'Fermentado'), ('Batido', 'Batido')], max_length=50, null=True, verbose_name='Tipo de Panificación'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='batter_density_g_cm3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Densidad Batido (g/cm3)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='batter_speed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Velocidad Batido'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='batter_time_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tiempo Batido (min)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='color_a',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Color a*'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='color_b',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Color b*'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='color_l',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Color L*'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='conclusion',
            field=models.TextField(blank=True, null=True, verbose_name='Conclusión Técnica'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='development_time_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tiempo Desarrollo (min)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='falling_number_sec',
            field=models.IntegerField(blank=True, null=True, verbose_name='Falling Number (seg)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='fermentation_humidity_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humedad Cámara (%)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='fermentation_temp_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temp. Fermentación (°C)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='fermentation_time_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tiempo Fermentación (min)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='final_volume_cc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Volumen Final (cc)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='final_weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Cocido (g)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='gluten_dry_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Gluten Seco (%)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='gluten_index_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Gluten Index'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='gluten_wet_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Gluten Húmedo (%)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='granulometry_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Granulometría (%)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='humidity_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Humedad (%)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='kneading_temp_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temp. Masa (°C)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='kneading_time_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tiempo Amasado (min)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='l_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor L (Extensibilidad)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='mold_diameter_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Diámetro Molde (cm)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='oven_temp_c',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temp. Horno (°C)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='oven_time_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tiempo Horno (min)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='p_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor P (Tenacidad)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='piece_weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Pieza (g)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='pl_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Relación P/L'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='protein_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Proteína (%)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='raw_weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Peso Crudo (g)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='scoring_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Calificación Greñado (1-10)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='sobado_turns',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vueltas de Sobado'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='stability_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Estabilidad (min)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='starch_damage_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Daño Almidón (%)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='w_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor W'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='water_absorption_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Absorción de Agua (%)'),
        ),
        migrations.AddField(
            model_name='ensayo',
            name='zeleny_ml',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Zeleny (ml)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca / Proveedor'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones técnicas'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recommended_dosage_ppm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dosis Recomendada (PPM)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='technical_sheet',
            field=models.FileField(blank=True, null=True, upload_to='tech_sheets/', verbose_name='Ficha Técnica (PDF)'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('Harina', 'Harina'), ('Ingrediente General', 'Ingrediente General'), ('Aditivo', 'Aditivo'), ('Mejorador', 'Mejorador'), ('Enzimático', 'Enzimático')], default='Ingrediente General', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre'),
        ),
        migrations.AddField(
            model_name='project',
            name='frequency',
            field=models.CharField(choices=[('Semanal', 'Semanal'), ('Quincenal', 'Quincenal'), ('Mensual', 'Mensual'), ('Única', 'Única')], default='Mensual', max_length=50, verbose_name='Frecuencia'),
        ),
        migrations.AddField(
            model_name='project',
            name='objective',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivo Principal'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Capacitación', 'Capacitación'), ('Seguimiento', 'Seguimiento'), ('Consulta', 'Consulta'), ('Desarrollo', 'Desarrollo')], default='Consulta', max_length=50, verbose_name='Tipo de Proyecto'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Curso', 'En Curso'), ('Terminado', 'Terminado'), ('Cancelado', 'Cancelado')], default='En Curso', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre / Razón Social'),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código de Ensayo'),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Problema/Objetivo'),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ensayos', to='lab.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='ensayodetail',
            name='dosage_ppm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Dosificación (PPM)'),
        ),
        migrations.AlterField(
            model_name='ensayodetail',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lab.ingredient', verbose_name='Ingrediente'),
        ),
        migrations.AlterField(
            model_name='ensayodetail',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Cantidad (KG)'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='default_price',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Precio Base'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='is_base_flour',
            field=models.BooleanField(default=False, help_text='Indica si se usa como base para cálculos de PPM', verbose_name='Es Harina Base'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre del Ingrediente'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='KG', max_length=10, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='lab.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre del Proyecto'),
        ),
        migrations.AlterField(
            model_name='projectingredientprice',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Precio Específico'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de la Visita')),
                ('start_time', models.TimeField(verbose_name='Hora Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora Fin')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción de la actividad')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='lab.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Agenda de Visitas',
            },
        ),
    ]
