# Generated by Django 6.0.1 on 2026-02-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_remove_client_contact_name_remove_client_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ensayodetail',
            name='dosage_ppm',
        ),
    ]
