# Generated by Django 6.0.1 on 2026-02-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0006_ensayo_evaluation_data_ensayo_final_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ensayoimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='ensayo',
            name='kneading_time_min',
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Puntaje Final'),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='gluten',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='kneading_time_v1_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Amasado Vel 1 (min)'),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='kneading_time_v2_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Amasado Vel 2 (min)'),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='pl_relacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='w_fuerza',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ensayodetail',
            name='quantity',
            field=models.DecimalField(decimal_places=9, max_digits=15, verbose_name='Cantidad (KG)'),
        ),
        migrations.AlterField(
            model_name='ensayoimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nota'),
        ),
    ]
