# Generated by Django 6.0.1 on 2026-02-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0009_client_contact_name_client_phone_client_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='contacts_data',
            field=models.JSONField(blank=True, default=list, verbose_name='Agenda de Contactos'),
        ),
    ]
