# Generated by Django 6.0.1 on 2026-02-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0011_visit_client_visit_objective_visit_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fixed_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Honorarios Fijos'),
        ),
        migrations.AddField(
            model_name='visit',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Gastos / Viáticos'),
        ),
        migrations.AddField(
            model_name='visit',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Honorarios / Facturable'),
        ),
    ]
