# Generated by Django 5.1.6 on 2026-02-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_visit_kilometers'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE lab_project ADD COLUMN IF NOT EXISTS technical_observations text;",
                    reverse_sql="ALTER TABLE lab_project DROP COLUMN IF EXISTS technical_observations;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='project',
                    name='technical_observations',
                    field=models.TextField(blank=True, null=True, verbose_name='Observaciones Técnicas / Conclusiones'),
                ),
            ]
        ),
    ]
