# Generated by Django 5.1.6 on 2026-02-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_visit_kilometers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technical_observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Técnicas / Conclusiones'),
        ),
    ]
