# Generated by Django 5.1.6 on 2026-02-09 18:08

from django.db import migrations, models


class PostgresSeparateDatabaseAndState(migrations.SeparateDatabaseAndState):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            for operation in self.database_operations:
                operation.database_forwards(app_label, schema_editor, from_state, to_state)
        else:
            for operation in self.state_operations:
                operation.database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        if schema_editor.connection.vendor == 'postgresql':
            for operation in reversed(self.database_operations):
                operation.database_backwards(app_label, schema_editor, from_state, to_state)
        else:
            for operation in reversed(self.state_operations):
                operation.database_backwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0013_visit_kilometers'),
    ]

    operations = [
        PostgresSeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE lab_project ADD COLUMN IF NOT EXISTS technical_observations text;",
                    reverse_sql="ALTER TABLE lab_project DROP COLUMN IF EXISTS technical_observations;",
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='project',
                    name='technical_observations',
                    field=models.TextField(blank=True, null=True, verbose_name='Observaciones Técnicas / Conclusiones'),
                ),
            ]
        ),
    ]
