# Generated by Django 5.1.6 on 2026-02-12 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0015_technicalreport'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # Skip SQL if tables already exist
            state_operations=[
                migrations.CreateModel(
                    name='Complaint',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega')),
                        ('loading_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Carga')),
                        ('batch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lote / Partida')),
                        ('flour_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Harina')),
                        ('product_made', models.CharField(blank=True, max_length=255, null=True, verbose_name='Producto Elaborado')),
                        ('process_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de Proceso')),
                        ('description', models.TextField(blank=True, null=True, verbose_name='Descripción del Reclamo')),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='lab.project', verbose_name='Proyecto')),
                    ],
                    options={
                        'verbose_name': 'Reclamo',
                        'verbose_name_plural': 'Reclamos Técnicos',
                        'ordering': ['-loading_date', '-created_at'],
                    },
                ),
                migrations.CreateModel(
                    name='ComplaintImage',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('image', models.ImageField(upload_to='complaint_photos/', verbose_name='Imagen Reclamo')),
                        ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nota')),
                        ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lab.complaint')),
                    ],
                ),
            ]
        ),
    ]
