# Generated by Django 5.1.6 on 2026-02-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0018_complaint_traceability'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contacto (Nombre y Tel)'),
        ),
    ]
