# Generated by Django 5.1.6 on 2026-02-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0020_complaint_direct_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintimage',
            name='image',
            field=models.URLField(max_length=1000, verbose_name='URL Imagen Reclamo'),
        ),
        migrations.AlterField(
            model_name='ensayoimage',
            name='image',
            field=models.URLField(max_length=1000, verbose_name='URL de Imagen'),
        ),
    ]
