# Generated by Django 5.1.6 on 2026-03-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0021_alter_complaintimage_image_alter_ensayoimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintimage',
            name='image',
            field=models.CharField(max_length=500, verbose_name='Ruta/URL Imagen'),
        ),
        migrations.AlterField(
            model_name='ensayoimage',
            name='image',
            field=models.CharField(max_length=500, verbose_name='Ruta/URL de Imagen'),
        ),
    ]
