# Generated by Django 5.1.6 on 2026-05-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0023_projectbudget_budgetitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Datos Específicos del Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Capacitación', 'Capacitación'), ('Seguimiento', 'Seguimiento'), ('Consulta', 'Consulta'), ('Desarrollo', 'Desarrollo'), ('Control', 'Control'), ('Reclamo', 'Reclamo')], default='Consulta', max_length=50, verbose_name='Tipo de Proyecto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Curso', 'En Curso'), ('Terminado', 'Terminado'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='En Curso', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('Técnica', 'Técnica'), ('Comercial', 'Comercial'), ('Seguimiento', 'Seguimiento'), ('Llamada', 'Llamada'), ('Prueba', 'Prueba'), ('Otro', 'Otro')], default='Técnica', max_length=50, verbose_name='Tipo de Visita'),
        ),
    ]
