# Generated by Django 5.1.6 on 2026-05-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0024_project_metadata_alter_project_project_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='legal_name_ins',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Legal / INS'),
        ),
    ]
