# Generated by Django 5.1.6 on 2026-08-17 16:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0025_ingredient_legal_name_ins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='loading_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha Carga'),
        ),
        migrations.AlterField(
            model_name='ensayo',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='technicalreport',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha del Informe'),
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('material', 'Material/Insumo'), ('viaje', 'Viaje/Transporte'), ('servicio', 'Servicio Externo'), ('otro', 'Otro')], default='material', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_expenses', to='lab.project')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
